setup-ant: update to support libsuperuser git submodule
closes #152 https://github.com/guardianproject/lildebi/pull/152

diff --git a/setup-ant b/setup-ant
--- a/setup-ant
+++ b/setup-ant
@@ -1,4 +1,29 @@
 #!/bin/sh
 
-# make sure your Android SDK tools path is set in ANDROID_HOME
-android update project --path . --name LilDebi
+if ! which android > /dev/null; then
+    if [ -z $ANDROID_HOME ]; then
+        if [ -e ~/.android/bashrc ]; then
+            . ~/.android/bashrc
+        else
+            echo "'android' not found, ANDROID_HOME must be set!"
+            exit
+        fi
+    else
+        export PATH="${ANDROID_HOME}/tools:$PATH"
+    fi
+fi
+
+projectname=`sed -n 's,.*name="app_name">\(.*\)<.*,\1,p' res/values/strings.xml`
+
+# fetch target from project.properties
+eval `grep '^target=' project.properties`
+
+echo "Setting up build for $projectname"
+echo ""
+
+for f in `find * -name project.properties`; do
+    projectdir=`dirname $f`
+    echo "Updating ant setup in $projectdir:"
+    android update lib-project -p $projectdir -t $target
+done
+android update project -p . --subprojects --name "$projectname" --target $target
